import{S as b,i as y,a as v}from"./assets/vendor-c145bea9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const a=document.querySelector(".loader"),d=document.querySelector(".form"),u=document.querySelector(".gallery"),c=document.querySelector(".load-more");let p;const L=async r=>await v.get("https://pixabay.com/api/",{params:r}),m=r=>{L(r).then(t=>(r.page===Math.ceil(t.data.totalHits/40)&&(y.error({message:"We're sorry, but you've reached the end of search results.",position:"center"}),c.style.display="none",a.style.display="none"),t.data)).then(t=>{const n=S(t.hits);n.length<1?(y.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),a.style.display="none"):(u.insertAdjacentHTML("beforeend",n),r.page<Math.ceil(t.totalHits/40)&&(c.style.display="block"),a.style.display="none",p&&p.refresh(),r.page>1&&window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"}))}).catch(t=>{console.log(t)})};let l={key:"41631198-f5cd04d694ed896bf4215baa6",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40};const w=r=>{r.preventDefault(),c.style.display="none",u.children.length>0&&(u.innerHTML=""),a.style.display="inline-block",l.q=d.searchQuery.value,l.page=1,d.reset(),m(l)},x=()=>{a.style.display="inline-block",l.page++,m(l)};d.addEventListener("submit",w);c.addEventListener("click",x);function S(r){return r.reduce((t,n)=>{const{largeImageURL:i,webformatURL:e,tags:o,likes:s,views:f,comments:g,downloads:h}=n;return t+`<li class="gallery-item">
        <a href="${i}"> 
          <img class="gallery-img" src="${e}" alt="${o}" />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${s}</span></p>
          <p>Views: <span class="text-value">${f}</span></p>
          <p>Comments: <span class="text-value">${g}</span></p>
          <p>Downloads: <span class="text-value">${h}</span></p>
        </div>
      </li>`},"")}document.addEventListener("DOMContentLoaded",()=>{p=new b(".gallery a")});
//# sourceMappingURL=commonHelpers.js.map
