import{S as b,i as d,a as L}from"./assets/vendor-c145bea9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const r=document.querySelector(".loader"),p=document.querySelector(".form"),u=document.querySelector(".gallery"),c=document.querySelector(".load-more");let y;const v=async s=>await L.get("https://pixabay.com/api/",{params:s}),g=async s=>{try{const t=await v(s),a=Math.ceil(t.data.totalHits/40);s.page===a&&(d.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c.style.display="none",r.style.display="none");const n=t.data,e=S(n.hits);e.length<1?(d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.style.display="none"):(u.insertAdjacentHTML("beforeend",e),s.page<Math.ceil(n.totalHits/40)&&(c.style.display="block"),r.style.display="none",y&&y.refresh(),s.page>1&&window.scrollBy({top:2*document.querySelector(".gallery-item").getBoundingClientRect().height,behavior:"smooth"}))}catch(t){console.log(t)}};let i={key:"41631198-f5cd04d694ed896bf4215baa6",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40};const w=s=>{s.preventDefault(),c.style.display="none",u.children.length>0&&(u.innerHTML=""),r.style.display="inline-block";const t=p.searchQuery.value;if(t.includes(" ")){d.error({message:"Search query cannot contain spaces. Please try again!",position:"topRight"}),r.style.display="none";return}i.q=t,i.page=1,p.reset(),g(i)},x=()=>{r.style.display="inline-block",i.page++,g(i)};p.addEventListener("submit",w);c.addEventListener("click",x);function S(s){return s.reduce((t,a)=>{const{largeImageURL:n,webformatURL:e,tags:o,likes:l,views:m,comments:f,downloads:h}=a;return t+`<li class="gallery-item">
        <a href="${n}"> 
          <img class="gallery-img" src="${e}" alt="${o}" />
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${l}</span></p>
          <p>Views: <span class="text-value">${m}</span></p>
          <p>Comments: <span class="text-value">${f}</span></p>
          <p>Downloads: <span class="text-value">${h}</span></p>
        </div>
      </li>`},"")}document.addEventListener("DOMContentLoaded",()=>{y=new b(".gallery a")});
//# sourceMappingURL=commonHelpers.js.map
